---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    state: present

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker CE and related packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose plugin (if not already available)
  apt:
    name: docker-compose-plugin
    state: present
  ignore_errors: yes

- name: Create directory for RAG project
  file:
    path: "{{ rag_project_dir }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"

- name: Clone RAG project repository
  git:
    repo: "{{ rag_repo_url }}"
    dest: "{{ rag_project_dir }}"
    version: "main"
  when: rag_repo_url is defined

- name: Update GCP instance metadata with API key
  command: >
    gcloud compute instances add-metadata {{ inventory_hostname }}
    --zone {{ gcp_instance_zone }}
    --metadata API_KEY={{ api_key }}
  delegate_to: localhost
