---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE and related packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose plugin (if not already available)
  apt:
    name: docker-compose-plugin
    state: present
  ignore_errors: yes

- name: Create directory for RAG project
  file:
    path: "{{ rag_project_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone RAG project repository
  git:
    repo: "{{ rag_repo_url }}"
    dest: "{{ rag_project_dir }}"
    version: "main"
  when: rag_repo_url is defined

- name: Store API key in a temporary file
  copy:
    content: "{{ api_key }}"
    dest: "/tmp/api_key.txt"
    mode: "0600"
  delegate_to: localhost
  run_once: true

- name: Update GCP instance metadata with API key
  delegate_to: localhost
  command: >
    gcloud compute instances add-metadata {{ gcp_instance_name }}
    --zone {{ gcp_instance_zone }}
    --metadata-from-file=API_KEY=/tmp/api_key.txt
  run_once: true

- name: Remove temporary API key file
  file:
    path: "/tmp/api_key.txt"
    state: absent
  delegate_to: localhost
  run_once: true