name: Deploy to GCP

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Install Ansible and dependencies
        run: |
          sudo apt update && sudo apt install -y ansible python3-pip docker.io
          pip3 install --user --upgrade ansible
          ansible-galaxy collection install google.cloud

      - name: Deploy via Ansible
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          ansible-playbook playbook.yml -i inventory/gcp_compute.yaml
