name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.ip.or.hostname >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Deploy via Ansible
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          ansible-playbook playbook.yml -i inventories/production/hosts.ini -e api_key=${API_KEY}
